- action:
  - data_template:
      payload: leave
      topic: presence/{{ trigger.from_state.name }}
    service: mqtt.publish
  - data_template:
      message: '{{ trigger.from_state.name }} ist nicht zu Hause'
      title: <b>Abwesend</b>
    service: notify.telegram_tinker
  - data_template:
      message: '{{ trigger.from_state.name }} ist nicht zu Hause'
      title: <b>Abwesend</b>
    service: notify.telegram_pino
  alias: not_home
  id: '1527345680809'
  trigger:
  - entity_id: device_tracker.pino_ping, device_tracker.tinker_ping
    platform: state
    to: not_home
- action:
  - data_template:
      payload: join
      topic: presence/{{ trigger.from_state.name }}
    service: mqtt.publish
  - data_template:
      message: '{{ trigger.from_state.name }} ist zu Hause'
      title: <b>Anwesend</b>
    service: notify.telegram_tinker
  - data_template:
      message: '{{ trigger.from_state.name }} ist zu Hause'
      title: <b>Anwesend</b>
    service: notify.telegram_pino
  alias: home
  id: '1527345741832'
  trigger:
  - entity_id: device_tracker.pino_ping, device_tracker.tinker_ping
    platform: state
    to: home
