- id: '1527345680809'
  alias: not_home
  trigger:
  - entity_id: device_tracker.pino_ping, device_tracker.tinker_ping
    platform: state
    to: not_home
  action:
  - data:
      payload: leave
      topic: presence/{{ trigger.from_state.name }}
    service: mqtt.publish
  - data_template:
      message: '{{trigger.from_state.name}} ist nicht zu Hause'
      title: <b>Abwesend</b>
    service: notify.telegram_group
- id: '1527345741832'
  alias: home
  trigger:
  - entity_id: device_tracker.pino_ping, device_tracker.tinker_ping
    platform: state
    to: home
  action:
  - data:
      payload: join
      topic: presence/{{ trigger.from_state.name }}
    service: mqtt.publish
  - data_template:
      message: '{{trigger.from_state.name}} ist zu Hause'
      title: <b>Anwesend</b>
    service: notify.telegram_group
- id: '1537602560985'
  alias: cam door alert
  trigger:
  - entity_id: binary_sensor.door_cam
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: device_tracker.tinker_ping
    state: not_home
  action:
  - data: {}
    service: script.cam_door_snapshot
