homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 160
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin

  customize: !include customize.yaml

#zeroconf:

zone:
  - name: Home
    latitude: !secret latitude
    longitude: !secret longitude
    radius: 30

shopping_list:

panel_iframe: 
  lms:
    title: 'LMS' 
    icon: mdi:mixcloud
    url: !secret lms_url
  nodered:
    title: 'Node Red' 
    icon: mdi:auto-fix
    url: 'http://192.168.2.142:1880'

frontend:

config:

http:
  server_host: "::0" #listen only to ipv6
  base_url: !secret base_url
  server_port: 8123
  ip_ban_enabled: true
  login_attempts_threshold: 10
#  ssl_certificate: /home/homeassistant/.homeassistant/cert.pem
#  ssl_key: /home/homeassistant/.homeassistant/privkey.pem

ifttt:
  key: !secret ifttt_key

device_tracker:
  - platform: owntracks
    max_gps_accuracy: 500
    waypoints: True
  - platform: ping
    consider_home: 45
    count: 5
    hosts:
      Tinker_PING: 192.168.2.177
      Pino_PING: 192.168.2.1
#  - platform: nmap_tracker
#    hosts: 192.168.2.0/24
#    home_interval: 10
#    scan_options: " --privileged -sP "
  
updater:
  include_used_components: true

# Discover some devices automatically
discovery:

conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

#MariaDB
recorder:
  db_url: !secret mysql_url

  # Delete events and states older than 1 week
  #purge_keep_days: 7
  #purge_interval: 1

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

homematic:
  interfaces:
    wireless:
      host: 127.0.0.1
      port: 2001
      resolvenames: json
      #username: Admin
      #password: secret
  hosts:
    homegear:
      host: 127.0.0.1

mqtt: 
  broker: 127.0.0.1
  client_id: homeassistant
  keepalive: 3600
  username: !secret mqtt_username
  password: !secret mqtt_password
  
shell_command:
  restart_volumioone: ssh volumio@192.168.2.233 sudo '/sbin/reboot'
  cam_door_snapshot: curl -s http://192.168.2.164:8080/0/action/snapshot > /dev/null 
  
media_player:
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret
    
  - platform: squeezebox
    host: 192.168.2.142
    username: !secret lms_username
    password: !secret lms_password
    
telegram_bot:
  - platform: polling
    name : telegram
    parse_mode: html
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - 519101236
      - 462233907

notify:

  - name: telegram_pino
    platform: telegram
    chat_id: !secret telegram_pino   

  - name: telegram_tinker
    platform: telegram
    chat_id: !secret telegram_tinker

camera:
  - platform: mjpeg
    mjpeg_url: http://192.168.2.164:8081
    name: Door

binary_sensor: !include binary_sensors.yaml
sensor: !include sensors.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
