- platform: owntracks
  max_gps_accuracy: 500
  waypoints: True
- platform: ping
  consider_home: 45
  count: 5 
  hosts:
    Tinker_PING: 192.168.2.177
    Pino_PING: 192.168.2.1
#  - platform: nmap_tracker
#    hosts: 192.168.2.0/24
#    home_interval: 10
#    scan_options: " --privileged -sP "