- platform: spotify
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

- platform: squeezebox
  host: 192.168.2.142
  username: !secret lms_username
  password: !secret lms_password